"""empty message

Revision ID: 4f9cf7d10647
Revises: 
Create Date: 2021-08-20 12:51:52.339171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9cf7d10647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_db',
    sa.Column('Employee ID', sa.Integer(), nullable=False),
    sa.Column('Billable Rate (per hour)', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(length=60), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Start Time', sa.Time(), nullable=False),
    sa.Column('End Time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('Employee ID', 'Company')
    )
    op.create_table('users',
    sa.Column('User ID', sa.Integer(), nullable=False),
    sa.Column('First Name', sa.String(), nullable=False),
    sa.Column('Last Name', sa.String(), nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Date of Birth', sa.Date(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('User ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('billing_db')
    # ### end Alembic commands ###
